### ISSUE TITLE
Question about magnetoelastic energy

### ISSUE THREAD

**Issue by will-colea** [ubermag/ubermag#105]
Does ubermag include the OOMMF magnetoelastic extension? Are there any examples on implementing magnetoelastic energy into ubermag simulations? Thank you for your help.

**Comment by marijanbeg** [comment]
Hi @will-colea, magnetoelastic energy extension is in Ubermag is there: https://micromagneticmodel.readthedocs.io/en/latest/magnetoelastic.html

You can include it in the energy equation. There is no tutorial on how to use it, but if you can invent a small example we can use in documentation as well as for testing, that would be great. We are then going to include your examples in Ubermag and acknowledge you as the contributor.

**Comment by will-colea** [comment]
Sure I will need to start with a small tutorial for myself to make sure it is working properly. I will share it with you to review once I am finished. Thank you!

**Comment by marijanbeg** [comment]
Addressing this question in workshop.
