### ISSUE TITLE
Hysteresis Loop for [110] Direction: Asking for Advice

### ISSUE THREAD

**Issue by will-colea** [ubermag/ubermag#107]
This is not really an issue with ubermag, but more of asking for help on how to create a hysteresis loop for [110] direction. I am modifying an example that just extracts the x-direction magnetisation [100]. I am having some errors that might be more python related than ubermag related, but if you could please take a look at it and offer some advice on how to properly apply the field along the [110] and then extract the magnetisation along the [110] direction as well. May I please email my notebook to you for advice? Thank you for your time.

**Comment by catrevil** [comment]
Hey @will-colea!

Can you please post this question in [ubermag/help](https://github.com/ubermag/help)? That is where questions like this are best placed to be answered. When you do so, can you also post your current notebook there?

If you are unable to post an attachment, it would be helpful then to include the portion of your code that you've having issues with in constructing your hysteresis loop. Formatting it as a code-block using markdown (click the little m icon or search online for more information on this) will provide more clarity in reading the contents of the code-block.

Thanks in advance!

**Comment by will-colea** [comment]
Oh, sure. Thank you and will do! I appreciate it.
