### ISSUE TITLE
Move logging control to `ubermagutil`

### ISSUE THREAD

**Issue by lang-m** [ubermag/ubermag#132]
Currently, ubermag has a function to set-up basic logging (`ubermag.setup_logging`). I would suggest that we move this functionality to `ubermagutil` as it is more a "utility thing". Furthermore, `ubermag` would then again be an "empty" meta-package with the sole purpose of ensuring that a working set of packages is installed.

What do you think @marijanbeg and @fangohr ?

**Comment by marijanbeg** [comment]
I agree this is a good idea. Logging can then be used by multiple packages.
