### ISSUE TITLE
Import oommfc error

### ISSUE THREAD

**Issue by zkhodzhaev** [ubermag/ubermag#142]
Hello,

I followed the instruction on the website (to install ubermag), and the test went well:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/21960382/189542756-a18522aa-a33d-4721-ad66-7b774e8af93b.png">

But, import oommfc is giving out an error:
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/21960382/189542732-096ea04a-9820-4508-b484-009d572a2c84.png">

**Comment by fangohr** [comment]
Probably a mixture of incompatible versions of `oommfc` and other required packages. 

How did you install Ubermag? 

If this is a version problem, and if you used pip to install ubermag, I would try something like `pip install -U ubermag`: the ubermag package has a [list of dependencies](https://github.com/ubermag/ubermag/blob/master/pyproject.toml#L41) and should upgrade them as required.
