### ISSUE TITLE
Wrong relativistic wavelength expression found

### ISSUE THREAD

**Issue by KylinGuo** [ubermag/ubermag#153]
The relativistic wavelength expression is wrong given by  [Here](https://ubermag.github.io/api/_autosummary/mag2exp.ltem.relativistic_wavelength.html#mag2exp.ltem.relativistic_wavelength)

Please correct it. One could find the details at [Here](https://zhuanlan.zhihu.com/p/629008312)

**Comment by fangohr** [comment]
The link does not work. Please update and re-open the ticket at https://github.com/ubermag/help .
