### ISSUE TITLE
Hide private data in repositories

### ISSUE THREAD

**Issue by marijanbeg** [ubermag/ubermag#51]
It would be good to hide private data in all repositories, such as:
- codecov token
- Slack notifications token

Any thoughts?

**Comment by fangohr** [comment]
No idea. @takluyver ?

**Comment by takluyver** [comment]
Travis lets you either put sensitive information in the Travis web interface (where it's not visible, but accessible to the build), or encrypt it and put the encrypted form in the `.travis.yml` file.

https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml

I think other CI services have similar provisions.

**Comment by marijanbeg** [comment]
There is no private data anymore.
