### ISSUE TITLE
Dependent builds on TravisCI

### ISSUE THREAD

**Issue by marijanbeg** [ubermag/ubermag#52]
There was a (short) discussion on Slack about dependent builds on TravisCI. For instance, package A depends on package B. Package B is broken (Travis build failed). Should Travis run builds of package A?

I think Travis should always report failure for whatever the reason. I assume that Travis badge on GitHub is the indication whether everything is OK with the package. Also maybe package B failed because of some feature that is not required in package A.

Any thoughts?

**Comment by fangohr** [comment]
I agree.

**Comment by mb1a15** [comment]
I'm reopening this issue just to remind me that this needs to be done.

I am the only assignee now.

**Comment by fangohr** [comment]
I think Travis has now a feature that allows you to build a package automatically once per week or month. We could activate that: over time, we will notice failures in package B if A has changed, even if we didn't run the CI for B just after the the change in A automatically.

**Comment by marijanbeg** [comment]
Travis is used for development testing most of the time. Therefore all packages are installed from github via pip to have the most recent versions. For simplicity, dependent builds are not necessary.
