### ISSUE TITLE
Adding multiple energy terms (of the same type) to the Hamiltonian

### ISSUE THREAD

**Issue by marijanbeg** [ubermag/ubermag#6]
It should not be possible to add multiple exchange or DMI energy objects to the Hamiltonian. This enhancement is to restrict physically meaningless models as well as not to take care of whether specific calculators support multiple exchange energies.

Having multiple `Zeeman` or `Anisotropy` energies can be physically possible, so this restriction at the moment should be made only for `Exchange` and `Demag` objects.

**Comment by mb1a15** [comment]
Some micromagnetic packages allow having multiple terms of the same type in the Hamiltonian (finmag). Although for example, having multiple symmetric exchange energies in the system does not make sense, in micromagnetics it can be understood as adding two exchange energies that are defined only on mesh subregions (A=0 outside those regions)- different materials for example. Therefore, I think this restriction would also limit the capabilities of specific calculators.

**Comment by mb1a15** [comment]
Any thoughts?

**Comment by fangohr** [comment]
I would suggest that we don't impose any restrictions in the micromagnetic model for now. Instead, we can introduce such 'sanity' checks for the specific calculators, and then allow what is possible to compute with them. So in OOMMFC, we would forbid using multiple demag terms.

Actually, maybe we should include the relevant code that checks whether a term has been added multiple times into the micromagnetic model, but delegate the configuration of this to the derived calculator classes? That would give us one copy of the code that does the checking, and the configuration can be specific for each calculator.

**Comment by marijanbeg** [comment]
Terms are now distinguished by names. Because there is no restriction imposed by OOMMF, we are not going to limit the user as @fangohr suggested.
