### ISSUE TITLE
Compute critical lengths

### ISSUE THREAD

**Issue by fangohr** [ubermag/ubermag#71]
Would be useful for the user to have a function that computes critical lengths for a given material, i.e.

- exchange length (in soft and hard materials) [1]
- for helimagnetic materials the helix period.

[1] http://nmag.soton.ac.uk/nmag/current/manual/html/tutorial/doc.html#exchange-length

**Comment by mb1a15** [comment]
Should the interface for this be `system.critical_lengths()`?

Also, it might be better to use `characteristic_lengths` or `characteristic_lengthscales`.

**Comment by fangohr** [comment]
I like `characteristic_length_scales()`. We must teach people to use auto-complete (so long names are okay) and try to be consistent in translating english terms into function names.

**Comment by fangohr** [comment]
Or maybe it is exchange_length? Mike Donahue had some slides on this on Wednesday in York: the length scale originates from the competition of exchange with demag, or exchange with anisotropy or exchange with DMI. So it makes sense to have 'exchange' in the name.

**Comment by mb1a15** [comment]
The only possible problem with this could be that the user will need to ask for all characteristic lengths separately and hope he did not forget about some (like Bloch parameter, DMI length...).

**Comment by fangohr** [comment]
We could return a dictionary that contains the name of the interaction (or equation) as the key, and the value as a number. We could have an extra key that provides the minimum value out of those computed. Or we have two functions:
```exchange_length()``` which returns the minimum exchange length, and 
```exchange_lengths()``` which returns all (for example in a dictionary as outline above)

Not sure this is ideal yet, I just want to encourage our creative thinking :)

**Comment by rpep** [comment]
What about 'length_scales' ? I think characteristic_length_scales is too long even with autocomplete - it's nearly 30 characters.

**Comment by marijanbeg** [comment]
For this, only exchange length has a clear formula how it can be calculated. For simplicity, I would not implement this.
