### ISSUE TITLE
OOMMF can't run on conda-based installation in docker container

### ISSUE THREAD

**Issue by fangohr** [ubermag/ubermag#81]
We see the following error:

<pre>
/opt/conda/opt/oommf/app/oxs/linux-x86_64/oxs: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory\n<186> oommf.tcl 1.2.1.0  panic:\nchild process exited abnormally\
</pre>

at https://travis-ci.org/joommf/conda-install/builds/297964872#L3018

This originates from running tests (as in https://github.com/joommf/conda-install/blob/master/Makefile#L15) in a docker container created with this Dockefile (https://github.com/joommf/conda-install/blob/master/Dockerfile)

@marijanbeg - have you seen this before?

**Comment by marijanbeg** [comment]
I have never seen this error.

**Comment by fangohr** [comment]
Okay, got one step further. We can get rid of this error if we install `libx11-6`, which provides the `libX11.so.6` file:

https://github.com/joommf/conda-install/commit/317ec28035c4253b61abc0753871a64735c5f117

**Comment by fangohr** [comment]
We now run into a new error, where it appears that OOMMF is complaining about a non-threaded TK environment (see line 2487 in
https://travis-ci.org/joommf/conda-install/builds/298493976#L2487 )

I tried to install (manually) `tclthread` via apt-get, but that did not fix the problem.

@takluyver  - does this ring any bells?

**Comment by takluyver** [comment]
It does sound familiar. I think Max was compiling tcl/tk himself to get a
threaded build. We got a change into conda forge, if I recall correctly, to
enable threading. Check that it's installing tcl from conda forge, and
whether it's using 8.5 or 8.6.

**Comment by fangohr** [comment]
Thanks, @takluyver - that was the right hint. So it seems that we have installed `tk` from the default channel (https://travis-ci.org/joommf/conda-install#L963), not the conda-forge channel. 

Once that is addressed (through line 23 here in the Dockerfile https://github.com/joommf/conda-install/blob/master/Dockerfile#L23, and here in action when building the image: https://travis-ci.org/joommf/conda-install#L1017), 
we get the conda-forge tk (see https://travis-ci.org/joommf/conda-install#L1196) and the tests pass.

The question now is (I think): can we modify the conda recipe for `oommf` (at https://github.com/conda-forge/oommf-feedstock/blob/master/recipe/meta.yaml) to ensure that the conda-forge tk is installed when we run `conda install -c conda-forge oommf` ?

**Comment by takluyver** [comment]
I don't think it's possible to specify that a dependency needs to come from a particular channel, though I'd hope that if you have the `-c conda-forge` option, it will use that for dependencies as well. It may depend on the version numbers of tk in conda-forge and in the defaults channel.

Ideally, we'd like Anaconda to have a threaded build of Tk as well. I'm not sure who best to talk to about that.

Here was the pull request where we set up conda-forge for a threaded build, for reference: https://github.com/conda-forge/tk-feedstock/pull/18

**Comment by fangohr** [comment]
How about creating new tk package that is threaded and called `tk-threaded`? On Ubuntu/Debian, there is a `tcl-thread` package (and virtual package `tclthread`). 

If the threaded and unthreaded version are fundamentally incompatible, maybe we should separate them not by version numbers or channels (`default` vs `conda-forge`) but by name?

**Comment by takluyver** [comment]
I suspect that would be messy - there would be two packages with different names trying to install the same files. I don't know how conda handles that, but I can't see any good option. The `tk` package is a dependency of Python, so it has to be installed in a conda environment to use joommf.

Debian packaging can express relationships such as 'provides' and 'conflicts' which are not possible in conda, as far as I know. The more complex system allows Debian to have a set of different implementation packages which can satisfy the same dependency.

**Comment by fangohr** [comment]
That's useful information, thank you.

**Comment by fangohr** [comment]
Okay, I have added some notes in https://github.com/joommf/conda-install/blob/master/README.md to explain users which command to run to get the right tk version if they are in this situation. Not ideal, but at least it is documented.

**Comment by marijanbeg** [comment]
This should be fixed now with new OOMMF conda package.
