### ISSUE TITLE
welcome page / getting started

### ISSUE THREAD

**Issue by fangohr** [ubermag/ubermag#87]
We should review and improve our documentation. With Binder now being up and running very well, we should have a button for 'Try Jupyter-OOMMF', which starts up a binder instance in which users can play with a tutorial / some examples (as we have done with Finmag, for example).

We may want to point to a special starting notebook that explains how to use the notebook - I have attempted something similar [here](https://github.com/fangohr/introduction-to-python-for-computational-science-and-engineering/blob/master/Readme.md) where the [Launch Binder button](
https://mybinder.org/v2/gh/fangohr/introduction-to-python-for-computational-science-and-engineering/master?filepath=index.ipynb) takes users to a special notebook, that also explains how to use Jupyter (at least roughly).

**Comment by marijanbeg** [comment]
We have getting started and tutorials as a part of documentation.
