### ISSUE TITLE
Review new interface notebook for discretised field

### ISSUE THREAD

**Issue by fangohr** [ubermag/ubermag#89]
I like the content of https://discretisedfield.readthedocs.io/en/latest/ipynb/new_interface.html a lot - good to show how to create different visualisations etc.

Is this the current interface? If so, we should integrate the documentation better (rename). Also, it looks like I put some feedback into that notebook, which we should edit out.

**Comment by marijanbeg** [comment]
`discretisedfield` package documentation is completed.
