### ISSUE TITLE
Example: magnetisation field at remanence

### ISSUE THREAD

**Issue by fangohr** [ubermag/ubermag#90]
This could be a useful example to add to the documentation.

Question from gitter:  I am carrying out hysteresis study. I want to capture the magnetization distribution at remanence points.
What is the way to do so?

Prelimenary answer: Good question. The general approach is that you compute the hysteresis loop, plot the curve (as in https://oommfc.readthedocs.io/en/latest/ipynb/standard_problem1.html#Hysteresis-loop-plot), then try to narrow down the field that corresponds to remanence (maybe through further simulation/hysteresis loops with smaller steps). Then you need to look for the data file that is closed to the remanence configuration you are after, and inspect that.

**Comment by marijanbeg** [comment]
Hysteresis driver is not a part of OOMMF. It is the same with mumax3. Therefore, it is now a recommended way of simulating hysteresis using a for loop and hysteresis driver is removed.
