### ISSUE TITLE
docstrings Timedriver and plot_plane

### ISSUE THREAD

**Issue by fangohr** [ubermag/ubermag#91]
Just playing with https://github.com/joommf/oommfc/blob/master/docs/ipynb/standard_problem_fmr.ipynb and find the docstring for the Timedriver and the plot_plane is minimalistic. We should extend that.

We should also review and finalise other docstrings now that the API is more stable.

<img width="1051" alt="screen shot 2018-10-20 at 08 29 00" src="https://user-images.githubusercontent.com/4489119/47252284-77583680-d442-11e8-92e8-56eb371c096c.png">

**Comment by marijanbeg** [comment]
Fixed.
