### ISSUE TITLE
joommf.readthedocs.io missing

### ISSUE THREAD

**Issue by fangohr** [ubermag/ubermag#94]
We have a link to https://joommf.readthedocs.io/en/latest/?badge=latest from the github/joommf/joommf webpage, but the readthedocs entry does not exist.

This maybe the right place as a starting point for JOOMMF documentation - the name is right ;).

Maybe this can point to OOMMFC, and the other packages. Or we gather a collection of all notebooks (from discretised model etc) in here (copies!?) so that there is one place from which the functionality of the whole project (i.e. joommf=oommfc+mircromagneticmodel+discretisedfield+micromagneticdata etc) is accessible. If we copy documentation from the sub packages, we should automate this and have the authoritative documentation within each sub package, and then only copy relevant files to the joommf documentation to have them in the same place.

**Comment by marijanbeg** [comment]
This is part of ubermag now.
