### ISSUE TITLE
Overwriting results

### ISSUE THREAD

**Issue by marijanbeg** [ubermag/ubermag#95]
Now that we have a strict structure of the directory, there is a question how should we deal with the issue when we try to drive the system with the same name as the already existing directory. More precisely, when we drive the system, a directory with the name `system.name` is created and inside it, directories `drive-0`, `drive-1`, etc. are created. If somebody drives the system several times, and then comes back to the simulation after some time (or creates a new system with the same name) then a conflict occurs. There are two possible solutions to the problem:

1. When user drives the system, JOOMMF should warn him that the directory already exists and tell him that he should pass an argument `overwrite=True` to the `drive` method or change the name of the system object. If `overwrite=True`, the entire directory is going to be deleted and a new one created.

2. If for example we have `drive-5` as the last drive directory, then it is going to continue with `drive-6`. This can complicate things a lot later for the data analysis because the system can physically be very different.

**Comment by marijanbeg** [comment]
For convenience, `system` object should have `.clean()` method, which is going to delete all files belonging to that system.

**Comment by fangohr** [comment]
For option 2: When you say it complicates the data analysis, you mean because the micromagnetic model may have changed and thus the data is not directly comparable? For example, the length and shape of the m-state-vector may change?

**Comment by marijanbeg** [comment]
@fangohr, Yes, the system might have changed, or after several runs the user notices he made a mistake in the beginning and then changes a parameter. Or just keeps the name of all his system objects the same for any problem he solves and that directory just grows. There are a lot of scenarios that can make the data we need to analyse not sensible.

**Comment by marijanbeg** [comment]
Option 1 has been implemented on `master`.
