### ISSUE TITLE
JupyterLab and widgets installation

### ISSUE THREAD

**Issue by marijanbeg** [ubermag/ubermag#97]
When we use JupyterLab, the installation of widgets is complicated. In particular, we first need to install nodejs with apt-get (https://nodejs.org/en/) and then run a series of commands to enable widgets and k3d. It seems to me that this is going to complicate the installation of JOOMMF both via pip and via conda. Does anybody know if this can be simplified?

**Comment by fangohr** [comment]
@SylvainCorlay, @marcinofulus, @JasonGrout - any ideas, or pointers? This is about the 'easy' installation of the JOOMMF code, where ideally it can all be installed via pip or conda. Maybe it's not possible at this stage. Thanks!

**Comment by marijanbeg** [comment]
No simplification possible.
